### ISSUE TITLE
cpplint: whitespace/empty_loop_body is not do..while compatible 

### ISSUE THREAD

**Issue by mani-monaj** [ros/roslint#28]
The following code is does not pass `cpplint::whitespace/empty_loop_body` check:

``` c
do
{
...
}
while (cond);
```

Error:

```
Empty loop bodies should use {} or continue  [whitespace/empty_loop_body] [5]
```

**Comment by SGleissner-Leica** [comment]
I strongly suggest to re-open this issue. The error message says that the loop body is empty, but it is simply not. If you do not like do-while-loops, move this to another category, but please don't misuse the empty loop warning.
