### ISSUE TITLE
cpplint: Warns about using rand and suggests obsolete method

### ISSUE THREAD

**Issue by alexhenning** [ros/roslint#33]
It currently suggests using `rand_r` instead of `rand` since that should be more thread-safe. However, `rand_r` is deprecated according to the [man page](http://linux.die.net/man/3/rand_r). It instead recommends using `drand48_r`. It looks like it would be fairly easy to update in the [code](https://github.com/ros/roslint/blob/master/src/roslint/cpplint.py#L1552).

**Comment by mikepurvis** [comment]
If you switch your code to `drand48_r`, the linter will no longer trip, IIUC. So I'd just as soon wait for this to get fixed upstream in cpplint.

**Comment by alexhenning** [comment]
Alright, I'll close this then and we can wait for it to be fixed upstream.
