### ISSUE TITLE
0.10 release

### ISSUE THREAD

**Issue by mikepurvis** [ros/roslint#39]
Once the [current Indigo sync occurs](http://lists.ros.org/pipermail/ros-release/2015-August/004661.html):

- [x] Tag roslint 0.10.0.
- [x] Indigo release.
- [x] Jade release.
- [ ] Announcement to ros-users.

**Comment by jack-oquin** [comment]
+1 Sounds good.

**Comment by mikepurvis** [comment]
In shadow on Indigo and Jade:

http://www.ros.org/debbuild/indigo.html?q=roslint
http://www.ros.org/debbuild/jade.html?q=roslint

Announcement:

http://lists.ros.org/pipermail/ros-users/2015-August/069566.html
