### ISSUE TITLE
Longer python line limit

### ISSUE THREAD

**Issue by ugocupcic** [ros/roslint#42]
Hi,

Would it be possible to set a longer limit for the python line size? 80 is really small - even pep8 [says that 100 would be ok](https://www.python.org/dev/peps/pep-0008/#maximum-line-length).

Cheers

**Comment by jack-oquin** [comment]
While I personally like the 80-column limit and would prefer strict PEP-8 compliance by default, I see no harm in providing some kind of ``roslint_python()`` per-invocation option to allow longer lines.

**Comment by ugocupcic** [comment]
Hi @jack-oquin thanks for the comment. 

We are not really interested in adding some options to override defaults (we'd rather stick to the same set of rules as everyone else, otherwise there's no point having rules :) ). We just wanted to discuss the possibility of updating the general roslint policy to use 100 instead of 80 char. If I understand the pep8 line I pointed to, it would still be pep8 compliant (they seem to indicate it's a matter of choice for the team).

I find it quite hard to stick to 80 when using list comprehension
```python
 self.hand_controllers = {"effort": ["sh_{0}{1}_effort_controller".format(hand_joint_prefix, joint) for joint in self.joints for hand_joint_prefix in self.robot_joint_prefixes]`
```

**Comment by AndriyPt** [comment]
Hi,

A few more remarks to @ugocupcic comment
In most cases wrap these lines to 79 characters and keep them readable at the same time is challenging. And we have to solve these puzzles from time to time :) 

The change of the default from 79 to 99 characters is backward compatible (in the sense that it will not show errors during roslint check of the code written in 79 characters line limit fashion)

Thanks

**Comment by evenator** [comment]
+1 to 100 char lines. The spirit of PEP8 is readability, and occasional long lines are more readable than doing gymnastics to get below the limit. Raymond Hettinger gave good rationale for this in Beyond PEP8 at PyCon 2015.

A compromise might be to only warn when a certain number of lines or percentage of lines exceed 80 chars.

**Comment by mikepurvis** [comment]
We had previously set the limit to 120, actually:

https://github.com/ros/roslint/blob/master/cmake/roslint-extras.cmake.em#L71

I suspect that #37 has broken this. Can @alexhenning or someone else look into what the new option is for line length limit?

**Comment by AndriyPt** [comment]
@mikepurvis thank you for your answer.
I have just checked  on my source code and roslint is using 120 characters limit. 
The issue which I have is that we do not want to add all this CMake changes to our project and just run 
**rosrun roslint pep8 <path to file>** 
command to check particular file and of course it doesn't take into account extra settings from your CMake file :) 
So it might be good to have such utility as a part of the roslint package which will check just one file with  default settings which you have for all files during catkin_make.
Thanks again for pointing place where you have line limit settings.

**Comment by alexhenning** [comment]
@AndriyPt https://github.com/ros/roslint/pull/44 should allow you to run `rosrun roslint pep8` and use a max line length of 120.

**Comment by AndriyPt** [comment]
@alexhenning thanks for your PR. I have done the same for cpplint and removed default value from roslint-extras.cmake.em file. In this case default from scripts/cpplint are used in CMakeLists.txt file and **rosrun roslint cpplint <file path>**. I am suggesting to do the same in your PR.

**Comment by mikepurvis** [comment]
Should be resolved now for both Python and C++, pending a release.

**Comment by AndriyPt** [comment]
Thank you :)
