### ISSUE TITLE
How can I run roslint in CMakelists by catkin_tools?

### ISSUE THREAD

**Issue by wkentaro** [ros/roslint#48]
I couldn't find how to run roslint with catkin_tools at [ROS wiki](http://wiki.ros.org/roslint)
How can I run it?

with
```
roslint_cpp()
```
in CMakeLists.txt?

**Comment by davetcoleman** [comment]
+1 I'm curious too

**Comment by evenator** [comment]
I haven't tested this, but from reading through the CMake, I think you should be able to do it with

    catkin build <any desired catkin packages/args go here> --make-args roslint

I don't have a package to test this on at the moment, but let me know if it works.

**Comment by wkentaro** [comment]
It works. Thanks.
and below also works
```
# CMakeLists.txt
roslint_python()
roslint_add_test()
```
```
$ catkin run_tests <package> --no-deps -iv
```

**Comment by davetcoleman** [comment]
I can't find any documentation for it except on the command line, but I ``catkin-tools`` also has a built-in ``lint`` function. I'm not sure how since I can't find it in the code, either. But the following works:

```
catkin lint -W2
```

Which i can verify with the help page:
```
catkin -h
usage: catkin [-h] [-a] [--test-colors] [--force-color | --no-color]
              [build | clean | config | create | init | lint | list | locate | profile]
              ...

catkin command

optional arguments:
  -h, --help            show this help message and exit
  -a, --list-aliases    Lists the current verb aliases and then quits, all
                        other arguments are ignored
  --test-colors         Prints a color test pattern to the screen and then
                        quits, all other arguments are ignored
  --force-color         Forces catkin to output in color, even when the
                        terminal does not appear to support it.
  --no-color            Forces catkin to not use color in the output,
                        regardless of the detect terminal type.

catkin command:
  Call `catkin VERB -h` for help on each verb listed below:
  
    build	Builds a catkin workspace.
    clean	Deletes various products of the build verb.
    config	Configures a catkin workspace's context.
    create	Creates catkin workspace resources like packages.
    init	Initializes a given folder as a catkin workspace.
    **lint	Checks catkin packages for common errors**
    list	Lists catkin packages in the workspace or other arbitray folders.
    locate	Get the paths to various locations in a workspace.
    profile	Manage config profiles for a catkin workspace.
```

Does anyone know how these two functionalities differ or are the same?

**Comment by jack-oquin** [comment]
They are not the same. Catkin lint checks for catkin CMake errors. ROS lint checks C++ or Python usage.

**Comment by jack-oquin** [comment]
I have never run roslint from the catkin command. I usually do this:
```
cd ~/catkin_ws
catkin build
cd build/$PACKAGENAME
make roslint
```

**Comment by wkentaro** [comment]
maybe we can create a alias
```
# ~/.config/catkin/verb_aliases/99-my-aliases.yaml
roslint: build --verbose --make-args roslint --
```

**Comment by davetcoleman** [comment]
++1 to roslint alias!

At a minimum, we should copy this documentation to the [wiki](http://wiki.ros.org/roslint) or [readthedocs](https://catkin-tools.readthedocs.org).

**Comment by davetcoleman** [comment]
I tested both methods just now. The first one seems to compile and work, but none of the warnings or errors from roslint are displayed so it is not very useful:

```
# CMakeLists.txt
roslint_python()
roslint_add_test()
```
```
$ catkin run_tests <package> --no-deps -iv
```

The second method worked great, but it would be nice to have the ability to automatically run it as a test:
```
catkin build --this --no-deps --make-args roslint
```

**Comment by wkentaro** [comment]
>  it would be nice to have the ability to automatically run it as a test:

that is what `catkin run_tests` do, doesn't it?
to check the test result, we need to run `catkin_test_results build/<package>`.

**Comment by evenator** [comment]
To see console output from a `catkin tools` build, use the `--verbose` flag.

**Comment by davetcoleman** [comment]
I in fact was using the verbose flag:

    catkin run_tests <package> --no-deps -iv

Where ``v`` is verbose.
