### ISSUE TITLE
A LICENSE file missing in the repo

### ISSUE THREAD

**Issue by wasowski** [ros/roslint#57]
I cannot see the LICENSE file (explicit, including copyright holders and year).  This makes it hard to reuse the code from this repo lawfully.

**Comment by mikepurvis** [comment]
The repo is marked as BSD in the `package.xml` file, which is the convention for ROS packages.

The individual files in the `src/roslint` path are all BSD licensed, and include their own headers with the specific holders and years.

Is there a tool or process you're using which requires something more explicit than this?

**Comment by wasowski** [comment]
I wanted to reuse some files (but actually outside src/) and I did not know how to attribute them in line with the license. First problem was which variant of BSD -- this I can kinda guess, but the license also requires attributing the copyright holders to be reproduced not just the license text (AFAIR).  This does not matter anymore as I am not reusing the files.  So close, if you don't think it is worth fixing.

**Comment by mikepurvis** [comment]
I have never bothered explicitly tagging build scripts and other metadata type stuff like launch files, I suppose on the theory that there's just nothing unique enough in there to even really lay claim to. That said, for packages like this one which expose entire cmake functions via catkin's `CFG_EXTRAS` mechanism, those have probably crossed the line from build script into source file, and should therefore have a properly license header.

**Comment by wasowski** [comment]
Yeah, that was exactly the file I was looking into (although I decided to implement my functions slightly differently, as my case was simpler).  

I always thought that dropping a toplevel LICENSE file was a solution for such nuisance.  Thus my comment.
