### ISSUE TITLE
Release roslint into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros/roslint#61]
This is a friendly reminder that the Melodic buildfarm is [now available](https://discourse.ros.org/t/melodic-morenia-buildfarm-available/4248).  It would be great to have a release of `roslint` into Melodic, as it is currently directly blocking 18 packages and indirectly blocking 28 packages (http://repositories.ros.org/status_page/blocked_releases_melodic.html).  Thank you!

**Comment by mikepurvis** [comment]
Yes, it's been on my radar— will do right away.

**Comment by mikepurvis** [comment]
https://github.com/ros/rosdistro/pull/17203

**Comment by clalancette** [comment]
Thank you!
