### ISSUE TITLE
Noetic source entry?

### ISSUE THREAD

**Issue by sloretz** [ros/roslint#70]
It looks like `roslint` [does not have a source entry](https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml) for Noetic [and is directly blocking 54 other repos](http://repositories.ros.org/status_page/blocked_source_entries_noetic.html?q=roslint&s=6&r=1). Mind adding a source entry for it? Will the noetic release use the `master` branch?

A source entry [signals to other packages it is being worked on](http://wiki.ros.org/UsingPython3/IdentifyDependencies#Determining_if_upstream_ROS_packages_support_Python_3), and makes it possible for downstream maintainers [to use `rosinstall_generator`](http://wiki.ros.org/UsingPython3/BuildUsingPython3#Download_source_code_of_dependencies) to download their dependencies while they work on Python 3 incompatibilities.

I didn't see any Python 3 syntax errors, and all the tests appeared to pass using Python 3 on Debian Buster. Is `roslint` already compatible with Python 3?

**Comment by mikepurvis** [comment]
Yes, roslint's two subcomponents (cpplint, pep8) are already fine for Python 3.

PR up for Noetic source entry: https://github.com/ros/rosdistro/pull/23256
